### PR TITLE
Fix small typings in contributing guide

### PR DESCRIPTION
**Pull request by VioletM**
### Description
Florian from the community reached out saying we have a typing in Contribution guide. I run the document through Grammarly. Typings are minor. 

### Related Issues

- Fixes #...
- Closes #...
- Resolves #...

### CODE REVIEW

**Review by AstrakhantsevaAA — DISMISSED** [review]
Thank you! ^_^

**Comment by burnash** [comment]
This is awesome, @VioletM thanks!

**Review by burnash — APPROVED** [review]
Looks good!

**Review by AstrakhantsevaAA — APPROVED** [review]
One more time :D

**Pull request merged**
