### PR TITLE
implements secret masking for auth helpers

### PR DESCRIPTION
**Pull request by willi-mueller**
### Related Issues

Follow-up to https://github.com/dlt-hub/dlt/issues/1474

### CODE REVIEW

**Comment by sh-rp** [comment]
I know this is not ready for review yet, but I think a better approach would be to use introspection to find the parts of a config that are secrets (they will be annotated as secrets) and then mask those. Another thing we could potentially do is to save all secrets that were retrieved from any of the providers in a list somewhere and just clean all log messages with regexes, this might be a bit slow though..

**Comment by willi-mueller** [comment]
> I know this is not ready for review yet, but I think a better approach would be to use introspection to find the parts of a config that are secrets (they will be annotated as secrets) and then mask those. Another thing we could potentially do is to save all secrets that were retrieved from any of the providers in a list somewhere and just clean all log messages with regexes, this might be a bit slow though..
> 
> So in short: Some implementation where we do not need to take care of every individual secret in any config would be good.

Thank you, that's helpful!

We have this PR for review where we mask the sensitive fields of known classes and config values: https://github.com/dlt-hub/verified-sources/pull/542. Is this better?

**Comment by sh-rp** [comment]
@sh-rp we need to make sure no secrets leak on validation and no secrets leak when calling __str__ on a ConfigurationObject.

**Comment by sh-rp** [comment]
closing in favor of this implementation: https://github.com/dlt-hub/dlt/pull/2027/

**Pull request closed without merging**
