### PR TITLE
320: add version to _dlt_loads table

### PR DESCRIPTION
**Pull request by codingcyclist**
Resolves [320](https://github.com/dlt-hub/dlt/issues/320)

### CODE REVIEW

**Review by rudolfix — CHANGES_REQUESTED** [review]
code changes are solid and all is ok there! thanks!
we still need to improve some tests. I enabled CI for your fork and a few tests are not passing
1. small linter issue (if you have poetry and make you can just do `make dev && make lint`)
2. common test problems: https://github.com/dlt-hub/dlt/actions/runs/5430315589/jobs/9969881019?pr=466

why the common tests are failing: each schema has a content hash used to detect schema changes. increasing the version changed the hash (when I load fixtures in tests, your migration modifies the content and we get a different hash - then tests that check hashes fail)
to fix: we need a v6 version of this fixture: ethereum_schema_v5.yml. I generate it with a dlt command:
```
dlt schema tests/common/cases/schemas/eth/ethereum_schema_v5.yml --remove-defaults
```
and save the output to new name. from it you can get the new content hash and put it into IMPORTED_VERSION_HASH_ETH_V5 constant (used by the tests)

btw. we'll upgrade our CI to be more friendly for PRs from forks: https://github.com/dlt-hub/dlt/issues/476

if the above looks too complicated or unclear just ping us, someone will take over the final fixes

**Comment by codingcyclist** [comment]
Hi @rudolfix Thanks a lot for your comments :) I took a stab at them and things look good locally. However, the nefly CI seems to be blocking the test from running on my fork. Is there anything I can do about that 🤔 ?

**Comment by rudolfix** [comment]
@codingcyclist I just unblocked CI. again... maybe it blocks PRs after some inactivity. will check out

**Review by rudolfix — APPROVED** [review]
LGTM!

**Pull request merged**
