### PR TITLE
Docs/Updated for slack alerts.

### PR DESCRIPTION
**Pull request by dat-a-man**
### Related Issues

- Fixes #...
- Closes #...
- Resolves #...

### CODE REVIEW

**Review by AstrakhantsevaAA — COMMENTED** [review]
Good! Add please also the link to the example:
https://dlthub.com/docs/examples/chess_production/

**Comment by dat-a-man** [comment]
added.

**Comment by dat-a-man** [comment]
> Good! Add please also the link to the example: https://dlthub.com/docs/examples/chess_production/

added

**Review by AstrakhantsevaAA — APPROVED** [review]
Very good!

**Pull request merged**
