### PR TITLE
feat(filesystem): use only netloc and scheme for fingerprint

### PR DESCRIPTION
**Pull request by IlyaFaer**
Towards #751 

Implements item 1

### CODE REVIEW

**Comment by IlyaFaer** [comment]
A couple of errors are happening, but they seem to be not related temporary problems with cloud databases.

**Comment by sh-rp** [comment]
@IlyaFaer could you update your branch to devel? I think the failing tests should go away then.

**Comment by IlyaFaer** [comment]
@sh-rp, @rudolfix, yes, it's passing now

**Review by rudolfix — APPROVED** [review]
LGTM!

**Pull request merged**
