### PR TITLE
docs(kafka): add Kafka source description

### PR DESCRIPTION
**Pull request by IlyaFaer**
Towards: https://github.com/dlt-hub/verified-sources/issues/273

### CODE REVIEW

**Review by burnash — APPROVED** [review]
Looks good, thanks for the docs, @IlyaFaer

**Comment by burnash** [comment]
@IlyaFaer please don't forget to link the page from https://github.com/dlt-hub/dlt/blob/devel/docs/website/sidebars.js#L49

**Comment by IlyaFaer** [comment]
So, let's merge it I suppose

**Review by burnash — APPROVED** [review]
All good, thank you!

**Pull request merged**
