### PR TITLE
fix ibis az problems on linux

### PR DESCRIPTION
**Pull request by sh-rp**
### Description
Reverse order of doing things when creating the ibis backend to see wether we can fix the problems with azure.

### CODE REVIEW

**Review by rudolfix — CHANGES_REQUESTED** [review]
I merged a hack into destinations.yaml that links certs in a proper place. IMO you should remove it and run the CI again

**Comment by rudolfix** [comment]
@sh-rp now it fails again...

**Comment by sh-rp** [comment]
¯\_(ツ)_/¯

**Comment by rudolfix** [comment]
@sh-rp heh that was tricky. actually `SET` was executed on a clone of the connection, while `ibis` was using another clone. And `SET` is not shared. pls check my commit and review

**Review by sh-rp — COMMENTED** [review]
looks good, the tests also pass, thanks for figuring this out!

**Review by rudolfix — APPROVED** [review]
LGTM!

**Pull request merged**
